docker inspect orderer.example.com | grep IPAddress
docker inspect orderer2.example.com | grep IPAddress
docker inspect orderer3.example.com | grep IPAddress
docker inspect orderer4.example.com | grep IPAddress
docker inspect orderer5.example.com | grep IPAddress
docker inspect ca.org1.example.com | grep IPAddress
docker inspect ca.org2.example.com | grep IPAddress
docker inspect peer0.org1.example.com | grep IPAddress
docker inspect peer1.org1.example.com | grep IPAddress
docker inspect peer0.org2.example.com | grep IPAddress
docker inspect peer1.org2.example.com | grep IPAddress